<?php
/**
 * Artisan command to scaffold the unified ArtisanPack UI configuration file.
 *
 * @since      2.0.0
 * @package    ArtisanPackUI\Core
 */

namespace ArtisanPackUI\Core\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Str;
use Symfony\Component\Console\Attribute\AsCommand;

#[AsCommand( name: 'artisanpack:scaffold-config' )]
class ScaffoldConfigCommand extends Command
{
	/**
	 * The name and signature of the console command.
	 *
	 * @var string
	 */
	protected $signature = 'artisanpack:scaffold-config
                            {--force : Overwrite existing keys in the configuration file.}';

	/**
	 * The console command description.
	 *
	 * @var string
	 */
	protected $description = 'Scaffolds the artisanpack.php config file with default settings from all installed ArtisanPack UI packages.';

	/**
	 * Execute the console command.
	 *
	 * @return int
	 */
	public function handle(): int
	{
		$this->info( 'Scaffolding ArtisanPack UI configuration file...' );

		$mainConfigPath = config_path( 'artisanpack.php' );

		// Ensure the base config file exists by publishing it first.
		if ( ! file_exists( $mainConfigPath ) ) {
			$this->call( 'vendor:publish', [
				'--tag' => 'artisanpack-config',
			] );
		}

		// Require the existing config file to get user's current customizations.
		$existingConfig = require $mainConfigPath;

		// Get the paths to all tagged package configuration files.
		$packageConfigPaths = ServiceProvider::pathsToPublish(
			null, 'artisanpack-package-config'
		);

		if ( empty( $packageConfigPaths ) ) {
			$this->warn( 'No ArtisanPack UI packages with tagged configurations found.' );
			return self::SUCCESS;
		}

		$newConfig   = $existingConfig;
		$changesMade = false;

		// CORRECTED: The loop now correctly gets the $sourcePath (key) and $destinationPath (value).
		foreach ( $packageConfigPaths as $sourcePath => $destinationPath ) {
			// Derive the package key from the file name, e.g., 'livewire-ui-components'.
			$packageKey = Str::of( basename( $sourcePath, '.php' ) )->kebab()->toString();

			if ( isset( $newConfig[ $packageKey ] ) && ! $this->option( 'force' ) ) {
				$this->line( "Skipping '{$packageKey}': Key already exists. Use --force to overwrite." );
				continue;
			}

			$newConfig[ $packageKey ] = require $sourcePath;
			$changesMade              = true;
			$this->info( "Added '{$packageKey}' configuration." );
		}

		if ( ! $changesMade ) {
			$this->info( 'No new configurations to add. Your file is up to date.' );
			return self::SUCCESS;
		}

		// Write the updated array back to the file.
		$this->writeConfigFile( $mainConfigPath, $newConfig );

		$this->info( 'Successfully updated config/artisanpack.php!' );

		return self::SUCCESS;
	}

	/**
	 * Writes the configuration array to a file.
	 *
	 * @param string $path   The path to the configuration file.
	 * @param array  $config The configuration array to write.
	 * @return void
	 */
	protected function writeConfigFile( string $path, array $config ): void
	{
		$export = var_export( $config, true );
		$export = preg_replace( '/^([ ]*)(.*)/m', '$1$1$2', $export );
		$array  = preg_split( "/\r\n|\n|\r/", $export );
		$array  = preg_replace( [ "/\s*array\s\($/", "/\)(,)?$/", "/\s=>\s$/" ], [ null, ']$1', ' => [' ], $array );
		$export = join( PHP_EOL, array_filter( [ "[" ] + $array ) );
		$export = preg_replace( '/=>\s*\[\s*\]/', '=> []', $export );

		$content = <<<PHP
<?php
/**
 * ArtisanPack UI Unified Configuration.
 *
 * This file is automatically generated by the artisanpack:scaffold-config command.
 * It contains the default settings from all installed ArtisanPack UI packages.
 * You can safely modify these values to customize your application.
 */
return {$export};

PHP;

		file_put_contents( $path, $content );
	}
}